"""
🧠 AI Quiz App – Main Entry Point
"""
import streamlit as st
import os
from dotenv import load_dotenv

# ─── Load environment variables ──────────────────────────────────────────────
load_dotenv()

# ─── Page Config (must be the first Streamlit command) ────────────────────────
st.set_page_config(
    page_title="AI Quiz App",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        "About": "AI-Powered Quiz Application built with Streamlit, MySQL & Google Gemini"
    }
)

# ─── Load Custom CSS ─────────────────────────────────────────────────────────
css_path = os.path.join(os.path.dirname(__file__), "assets", "style.css")
if os.path.exists(css_path):
    with open(css_path) as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

# ─── Environment Validation ──────────────────────────────────────────────────
def _check_env():
    """Check environment variables and return status."""
    checks = {
        "MYSQL_HOST": ("MySQL Host", True),
        "MYSQL_USER": ("MySQL User", True),
        "MYSQL_PASSWORD": ("MySQL Password", True),
        "NVIDIA_API_KEY": ("NVIDIA NIM API Key", True),
        "GOOGLE_CLIENT_ID": ("Google OAuth Client ID", False),
        "GOOGLE_CLIENT_SECRET": ("Google OAuth Secret", False),
    }
    issues = []
    for var, (label, required) in checks.items():
        val = os.getenv(var, "").strip()
        if not val and required:
            issues.append(f"❌ **{label}** (`{var}`) — missing")
        elif not val:
            issues.append(f"⚠️ {label} (`{var}`) — optional, not set")
    return issues

env_issues = _check_env()
critical_missing = [i for i in env_issues if i.startswith("❌")]
if critical_missing:
    st.error("⚠️ **Missing environment variables!** Check your `.env` file.")
    for issue in critical_missing:
        st.markdown(issue)
    st.info("Copy `.env.example` to `.env` and fill in the values. See the README for details.")

# ─── Sidebar ─────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("# 🧠 AI Quiz App")
    st.caption("Powered by Google Gemini")
    st.divider()

    # Show env status in sidebar
    with st.expander("🔧 Config Status"):
        for issue in env_issues:
            st.markdown(issue, unsafe_allow_html=True)
        if not env_issues:
            st.success("All configured ✅")

    if st.session_state.get("logged_in"):
        user = st.session_state.get("user", {})
        st.markdown(f"👋 **{user.get('name', 'User')}**")
        st.caption(f"Role: {user.get('role', 'user').title()}")
        if st.button("🚪 Logout", use_container_width=True):
            from utils.auth import logout
            logout()
            st.rerun()
    else:
        st.info("Please log in to get started.")

# ─── Main Content ────────────────────────────────────────────────────────────
st.markdown("""
<div style="text-align: center; padding: 2rem 0;">
    <h1 style="font-size: 3rem; font-weight: 800; 
        background: linear-gradient(135deg, #6C63FF, #00D2FF, #FF6584);
        -webkit-background-clip: text; -webkit-text-fill-color: transparent;
        margin-bottom: 0.5rem;">
        🧠 AI Quiz App
    </h1>
    <p style="font-size: 1.2rem; color: #A0A4B8; max-width: 600px; margin: 0 auto;">
        Test your knowledge with AI-generated quizzes. Personalized. Intelligent. Fun.
    </p>
</div>
""", unsafe_allow_html=True)

# ─── Feature Highlights ──────────────────────────────────────────────────────
st.markdown("")
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.markdown("""
    <div style="background: linear-gradient(135deg, #1A1D29, #22263A); 
        border: 1px solid rgba(108,99,255,0.15); border-radius: 16px; 
        padding: 1.5rem; text-align: center; height: 220px;">
        <div style="font-size: 2.5rem; margin-bottom: 0.5rem;">🤖</div>
        <h3 style="font-size: 1.1rem; margin-bottom: 0.5rem; color: #FAFAFA;">AI-Powered</h3>
        <p style="color: #A0A4B8; font-size: 0.85rem;">
            Questions generated by Google Gemini AI with intelligent explanations
        </p>
    </div>
    """, unsafe_allow_html=True)

with col2:
    st.markdown("""
    <div style="background: linear-gradient(135deg, #1A1D29, #22263A); 
        border: 1px solid rgba(0,210,255,0.15); border-radius: 16px; 
        padding: 1.5rem; text-align: center; height: 220px;">
        <div style="font-size: 2.5rem; margin-bottom: 0.5rem;">🎯</div>
        <h3 style="font-size: 1.1rem; margin-bottom: 0.5rem; color: #FAFAFA;">Personalized</h3>
        <p style="color: #A0A4B8; font-size: 0.85rem;">
            Quizzes tailored to your interests and skill level
        </p>
    </div>
    """, unsafe_allow_html=True)

with col3:
    st.markdown("""
    <div style="background: linear-gradient(135deg, #1A1D29, #22263A); 
        border: 1px solid rgba(255,101,132,0.15); border-radius: 16px; 
        padding: 1.5rem; text-align: center; height: 220px;">
        <div style="font-size: 2.5rem; margin-bottom: 0.5rem;">📊</div>
        <h3 style="font-size: 1.1rem; margin-bottom: 0.5rem; color: #FAFAFA;">Analytics</h3>
        <p style="color: #A0A4B8; font-size: 0.85rem;">
            Track your progress with detailed performance insights
        </p>
    </div>
    """, unsafe_allow_html=True)

with col4:
    st.markdown("""
    <div style="background: linear-gradient(135deg, #1A1D29, #22263A); 
        border: 1px solid rgba(0,200,83,0.15); border-radius: 16px; 
        padding: 1.5rem; text-align: center; height: 220px;">
        <div style="font-size: 2.5rem; margin-bottom: 0.5rem;">🏆</div>
        <h3 style="font-size: 1.1rem; margin-bottom: 0.5rem; color: #FAFAFA;">Leaderboard</h3>
        <p style="color: #A0A4B8; font-size: 0.85rem;">
            Compete with others and climb the rankings
        </p>
    </div>
    """, unsafe_allow_html=True)

# ─── How It Works ─────────────────────────────────────────────────────────────
st.markdown("")
st.markdown("")
st.markdown("### 🚀 How It Works")

step1, step2, step3, step4 = st.columns(4)

with step1:
    st.markdown("""
    **Step 1: Sign Up**  
    Create your account and select your interests
    """)

with step2:
    st.markdown("""
    **Step 2: Choose Quiz**  
    Pick a category and difficulty level
    """)

with step3:
    st.markdown("""
    **Step 3: Take Quiz**  
    Answer AI-generated questions with a timer
    """)

with step4:
    st.markdown("""
    **Step 4: Learn**  
    Review results with AI-powered explanations
    """)

# ─── Quick Stats (if logged in) ──────────────────────────────────────────────
if st.session_state.get("logged_in"):
    st.divider()
    try:
        from utils.quiz import get_user_stats, get_platform_stats

        user_stats = get_user_stats(st.session_state["user_id"])
        platform = get_platform_stats()

        st.markdown("### 📊 Your Quick Stats")
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Quizzes Taken", user_stats["total_quizzes"])
        c2.metric("Questions Answered", user_stats["total_attempted"])
        c3.metric("Avg. Score", f"{user_stats['avg_percentage']:.0f}%")
        c4.metric("Best Score", f"{user_stats['best_percentage']:.0f}%" if user_stats['best_percentage'] else "N/A")

        st.markdown("### 🌐 Platform Stats")
        p1, p2, p3, p4 = st.columns(4)
        p1.metric("Total Users", platform["total_users"])
        p2.metric("Total Questions", platform["total_questions"])
        p3.metric("Quizzes Completed", platform["total_quizzes"])
        p4.metric("Avg. Score", f"{platform['avg_score']}%")
    except Exception:
        pass
else:
    st.markdown("")
    st.markdown("")
    col_left, col_center, col_right = st.columns([1, 2, 1])
    with col_center:
        st.info("👈 Navigate to **Login** from the sidebar to get started!", icon="🔐")

# ─── Footer ───────────────────────────────────────────────────────────────────
st.markdown("---")
st.markdown(
    "<div style='text-align: center; color: #A0A4B8; font-size: 0.8rem;'>"
    "Built with ❤️ using Streamlit & Google Gemini AI"
    "</div>",
    unsafe_allow_html=True
)
