-- ============================================
-- AI Quiz Application – PostgreSQL Schema (Supabase)
-- ============================================
-- Run this ONCE in the Supabase SQL Editor.

-- ------------------------------------------
-- 1. Users
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT          NOT NULL,
    email         TEXT          NOT NULL UNIQUE,
    password      TEXT          DEFAULT NULL,   -- NULL when signed-in via Google
    google_id     TEXT          DEFAULT NULL UNIQUE,
    role          TEXT          NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    selected_topics JSONB       NOT NULL DEFAULT '[]'::jsonb,
    avatar_url    TEXT          DEFAULT NULL,
    created_at    TIMESTAMPTZ   DEFAULT now(),
    updated_at    TIMESTAMPTZ   DEFAULT now()
);

-- Auto-update updated_at on row change
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ------------------------------------------
-- 2. Categories
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT          NOT NULL UNIQUE,
    description   TEXT          DEFAULT NULL,
    icon          TEXT          DEFAULT '📚',
    created_at    TIMESTAMPTZ   DEFAULT now()
);

-- ------------------------------------------
-- 3. Questions
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS questions (
    question_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id    BIGINT        NOT NULL REFERENCES categories(category_id) ON DELETE CASCADE,
    question_text  TEXT          NOT NULL,
    options        JSONB         NOT NULL DEFAULT '[]',
    correct_answer TEXT          NOT NULL,
    explanation    TEXT          DEFAULT NULL,
    difficulty     TEXT          NOT NULL DEFAULT 'Medium' CHECK (difficulty IN ('Easy', 'Medium', 'Hard')),
    created_at     TIMESTAMPTZ   DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_questions_cat_diff ON questions (category_id, difficulty);

-- ------------------------------------------
-- 4. Quiz Sessions (one row per attempt)
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS quiz_sessions (
    session_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    category_id      BIGINT        NOT NULL REFERENCES categories(category_id) ON DELETE CASCADE,
    difficulty       TEXT          NOT NULL DEFAULT 'Medium' CHECK (difficulty IN ('Easy', 'Medium', 'Hard')),
    score            INT           NOT NULL DEFAULT 0,
    total_questions  INT           NOT NULL DEFAULT 0,
    time_taken       INT           DEFAULT NULL,   -- seconds
    date_taken       TIMESTAMPTZ   DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sessions_user    ON quiz_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_leaderboard ON quiz_sessions (user_id, score DESC);

-- ------------------------------------------
-- 5. Quiz Answers (one row per question)
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS quiz_answers (
    answer_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id       BIGINT        NOT NULL REFERENCES quiz_sessions(session_id) ON DELETE CASCADE,
    question_id      BIGINT        NOT NULL REFERENCES questions(question_id) ON DELETE CASCADE,
    selected_answer  TEXT          DEFAULT NULL,
    is_correct       BOOLEAN       NOT NULL DEFAULT FALSE
);

-- ------------------------------------------
-- Disable RLS (use app-level auth via Supabase anon key)
-- ------------------------------------------
ALTER TABLE users           ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories      ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions        ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_sessions    ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_answers     ENABLE ROW LEVEL SECURITY;

-- Allow full access via service_role or anon key (open policies for app-managed auth)
CREATE POLICY "Allow all for anon" ON users           FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON categories      FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON questions        FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON quiz_sessions    FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON quiz_answers     FOR ALL USING (true) WITH CHECK (true);

-- ------------------------------------------
-- Seed: Default Categories
-- ------------------------------------------
INSERT INTO categories (category_name, description, icon) VALUES
    ('Cybersecurity',        'Network security, ethical hacking, and cyber defense',       '🔒'),
    ('Programming',          'Coding concepts, algorithms, and data structures',            '💻'),
    ('AI & Machine Learning','Neural networks, deep learning, and intelligent systems',    '🤖'),
    ('Databases',            'SQL, NoSQL, database design and optimization',                '🗄️'),
    ('Networking',           'TCP/IP, routing, switching, and network protocols',            '🌐'),
    ('General Knowledge',    'Science, history, geography, and current affairs',             '📖'),
    ('Technology',           'Latest tech trends, gadgets, and innovations',                 '⚡'),
    ('Web Development',      'HTML, CSS, JavaScript, and modern web frameworks',             '🕸️')
ON CONFLICT (category_name) DO NOTHING;

-- ------------------------------------------
-- Seed: Default Admin User
-- password = bcrypt hash of "admin123"
-- ------------------------------------------
INSERT INTO users (name, email, password, role) VALUES
    ('Admin', 'admin@quizapp.com',
     '$2b$12$7rh2javPzVAY8dNAb8/GkuJSmhQ/F/yHNvXZ8doBC.KKx.To.0z0q',
     'admin')
ON CONFLICT (email) DO NOTHING;
